# Generated by Django 3.1.3 on 2020-11-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookPurchase',
            new_name='Purchase',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='readingbook',
            old_name='code_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='readingbook',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
