# Generated by Django 3.1.3 on 2020-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201107_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='code',
            name='is_deleted',
            field=models.BooleanField(default='false'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_actual',
            field=models.BooleanField(default='true'),
        ),
        migrations.AlterField(
            model_name='readingbook',
            name='is_actual',
            field=models.BooleanField(default='true'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='is_actual',
            field=models.BooleanField(default='true'),
        ),
    ]
