# Generated by Django 3.1.3 on 2020-11-13 18:06

from django.db import migrations

from book.data.books import BOOKS


def addBooks(apps, schema_editor):
    Book = apps.get_model("book", "book")

    for book in BOOKS:
        Book.objects.create(**book)


def removeBooks(apps, schema_editor):
    Book = apps.get_model("book", "book")

    Book.objects.get().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('book', '0005_auto_20201111_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bbk',
        ),
        migrations.RemoveField(
            model_name='book',
            name='udc',
        ),
        migrations.RunPython(
            addBooks,
            removeBooks
        )
    ]
