# Generated by Django 3.1.3 on 2020-11-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20201113_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='book',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ebooks',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='filename',
        ),
    ]
