# Generated by Django 3.1.3 on 2020-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20201130_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(to='book.Publisher'),
        ),
    ]
